version: '3.1'
services:
  app:
    container_name: machinery-ms
    image: durpyshark/machinery-ms
    build: ./
    ports:
      - "8085:8085"
    depends_on:
      - machinery_db_container
  machinery_db_container:
    image: postgres
    ports:
      - "5437:5437"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=machinery_db
    command: -p 5437