apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: machinery-db-container
  name: machinery-db-container
spec:
  ports:
  - name: "5437"
    port: 5437
    targetPort: 5437
  selector:
    io.kompose.service: machinery-db-container
status:
  loadBalancer: {}
